name: VariZoo
version: '1.1.3'
main: cn.variZoo.Main
api-version: '1.21'
folia-supported: true

commands:
  varizoo:
    description: Main command.
    aliases:
      - vz
    usage: /<command>
permissions:
  varizoo.reload:
    description: Allow the player to reload the plugin.
    default: op
  varizoo.help:
    description: Allow the player to get the help.
    default: true
  varizoo.skip.breed:
    description: Allow the player to breed animal without scale.
    default: op